services: 
  api: 
    build: .
    ports: 
      - "5000:5000"
    restart: unless-stopped
    volumes: 
      - "./data:/data"
  website: 
    depends_on: 
      - api
    environment: 
      - USERNAME=toto
      - PASSWORD=python
    image: "php:apache"
    ports: 
      - "80:80"
    volumes: 
      - "./student-list/website:/var/www/html"
version: "3"